info:
  app:
    name: Ecom-monolith
    description: Ecommerce Monolith Application
    version: 1.0.0


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      access: none
  info:
    env:
      enabled: true


spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ecomdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
