info:
  app:
    name: Ecom-monolith
    description: Ecommerce Monolith Application (Dev)
    version: 1.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/ecom_db
    username: ecom_user
    password: ecom_pass123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.ecom.monolith: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

aws:
  region: eu-central-1  # ✅ REQUIRED for S3 & SecretsManager client beans
  s3:
    bucket: ecom-dev-images
    image-folder: Product-images/
  cloudfront:
    domain: d3fvaxahagq49e.cloudfront.net
    key-pair-id: K1NWUILC6ZRCKA
    private-key-secret-name: monolith/cloudfront/private-key
    signed-url-expiration-seconds: 3600