spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

info:
  app:
    name: Ecom-monolith
    description: Ecommerce Monolith Application
    version: 1.0.0

logging:
  level:
    root: INFO
    com.ecom.monolith: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
    info:
      access: unrestricted

aws:
  region: us-east-1  # ✅ REQUIRED for S3 & SecretsManager client beans
  s3:
    bucket: ecom-dev-images
    image-folder: Product-images
  cloudfront:
    domain: d3fvaxahagq49e.cloudfront.net
    key-pair-id: K1NWUILC6ZRCKA
    private-key-secret-name: monolith/cloudfront/private-key
    signed-url-expiration-seconds: 3600

